DROP DATABASE IF EXISTS concesionario;
CREATE DATABASE concesionario DEFAULT CHAR SET utf8mb4;
USE concesionario;

CREATE TABLE datospersonales (
dni VARCHAR(9) NOT NULL PRIMARY KEY UNIQUE,
nombre VARCHAR(45) NOT NULL,
apellidos VARCHAR(45) NOT NULL,
domicilio VARCHAR(45),
fechaAlta DATE NOT NULL,
tipo VARCHAR(2)
);

CREATE TABLE director (
dni VARCHAR(9) PRIMARY KEY NOT NULL,
fechaCargo DATE NOT NULL,
CONSTRAINT fkDirector FOREIGN KEY (dni) REFERENCES datospersonales(dni) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE comercial (
dni VARCHAR(9) PRIMARY KEY NOT NULL,
comision FLOAT,
CONSTRAINT fkComercial FOREIGN KEY (dni) REFERENCES datospersonales(dni) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE cliente (
dni VARCHAR(9) PRIMARY KEY NOT NULL,
idCliente INT NOT NULL,
CONSTRAINT fkCliente FOREIGN KEY (dni) REFERENCES datospersonales(dni) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE oficina (
codOficina VARCHAR(4) PRIMARY KEY,
direccion VARCHAR(45),
fechaApertura VARCHAR(45) NOT NULL,
dniDirector VARCHAR(9) NOT NULL,
CONSTRAINT fkOficina FOREIGN KEY (dniDirector) REFERENCES director(dni) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE vendedor (
dni VARCHAR(9) PRIMARY KEY NOT NULL,
turno VARCHAR(1),
idOficina VARCHAR(4),
CONSTRAINT fkVendedor1 FOREIGN KEY (dni) REFERENCES datospersonales(dni) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fkVendedor2 FOREIGN KEY (idOficina) REFERENCES oficina(codOficina) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE titulo (
codTitulo VARCHAR(2) NOT NULL PRIMARY KEY,
descripcion VARCHAR(45)
);

CREATE TABLE tituloDirector (
codTitulo VARCHAR(2) NOT NULL,
dniDirector VARCHAR(9) NOT NULL,
PRIMARY KEY (codTitulo, dniDirector),
CONSTRAINT fkTitulo1 FOREIGN KEY (codTitulo) REFERENCES titulo(codTitulo) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fkTitulo2 FOREIGN KEY (dniDirector) REFERENCES director(dni) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE vehiculo (
numBastidor VARCHAR(15) NOT NULL PRIMARY KEY,
fabricante VARCHAR(45) NOT NULL,
modelo VARCHAR(45) NOT NULL,
color VARCHAR(45) NOT NULL,
precioRecomendado DECIMAL(9,2) NOT NULL
);

CREATE TABLE venta (
numBastidor VARCHAR(15) PRIMARY KEY,
fechaVenta DATE NOT NULL,
dniVendedor	VARCHAR(9) NOT NULL,
dniCliente VARCHAR(9) NOT NULL,
precioVenta DECIMAL(7,2) NOT NULL,
CONSTRAINT fkVenta1 FOREIGN KEY (numBastidor) REFERENCES vehiculo(numBastidor) ON DELETE CASCADE ON UPDATE CASCADE, 
CONSTRAINT fkVenta2 FOREIGN KEY (dniVendedor) REFERENCES vendedor(dni) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fkVenta3 FOREIGN KEY (dniCliente) REFERENCES cliente(dni) ON DELETE CASCADE ON UPDATE CASCADE
);