DROP DATABASE IF EXISTS instituto;
CREATE DATABASE instituto DEFAULT CHAR SET utf8mb4;
USE instituto;

CREATE TABLE profesor (
idProf INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombreEmp VARCHAR(45),
telefono VARCHAR(14) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
dni_prof VARCHAR(9) UNIQUE
);

CREATE TABLE curso (
codCurso CHAR(5) NOT NULL PRIMARY KEY,
nomCurso VARCHAR(50) NOT NULL,
nivelEducativo VARCHAR(15) NOT NULL,
CONSTRAINT ckNivel CHECK (nivelEducativo IN('BASICO', 'MEDIO', 'SUPERIOR'))
);

CREATE TABLE aula (
codAula CHAR(10) PRIMARY KEY,
numPlazas INT NOT NULL,
numOrdenadores INT
);

CREATE TABLE beca (
idBeca INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
importe DECIMAL(5,2) NOT NULL,
CONSTRAINT ckImporte CHECK (importe >= 0 AND importe < 1000),
fechaBeca DATE NOT NULL DEFAULT (current_date())
);

CREATE TABLE modulo (
codMod CHAR(5) NOT NULL PRIMARY KEY,
idProf INT NOT NULL,
nomMod VARCHAR(45) NOT NULL,
CONSTRAINT fkModulo FOREIGN KEY (idProf) REFERENCES profesor(idProf) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE tema (
codTema CHAR(5) NOT NULL PRIMARY KEY,
codMod CHAR(5) NOT NULL,
tituloTema VARCHAR(45),
CONSTRAINT fkTema FOREIGN KEY (codMod) REFERENCES modulo(codMod) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE grupo (
codCurso CHAR(5),
letra CHAR(1) NOT NULL,
codAula CHAR(10),
PRIMARY KEY (codCurso, letra),
CONSTRAINT fkGrupo1 FOREIGN KEY (codCurso) REFERENCES curso(codCurso) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fkGrupo2 FOREIGN KEY (codAula) REFERENCES aula(codAula) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE alumno (
codExpediente VARCHAR(10) NOT NULL PRIMARY KEY,
nomAlumno VARCHAR(45),
telAlumno VARCHAR(14),
fechaNacimiento DATE NOT NULL,
codExpedienteDelegado VARCHAR(10),
idBeca INT,
codCurso CHAR(5),
letra CHAR(1),
CONSTRAINT fkAlumno1 FOREIGN KEY (codExpedienteDelegado) REFERENCES alumno(codExpediente) ON UPDATE CASCADE ON DELETE RESTRICT,
CONSTRAINT fkAlumno2 FOREIGN KEY (idBeca) REFERENCES beca(idBeca) ON UPDATE CASCADE ON DELETE RESTRICT,
CONSTRAINT fkAlumno3 FOREIGN KEY (codCurso, letra) REFERENCES grupo(codCurso, letra) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE cursa (
codTema CHAR(5) NOT NULL PRIMARY KEY,
codMod CHAR(5) NOT NULL,
tituloTema CHAR(45),
CONSTRAINT fkCursa FOREIGN KEY (codMod) REFERENCES modulo(codMod) ON UPDATE CASCADE ON DELETE RESTRICT
);

DROP TABLE cursa;
DROP TABLE alumno;
DROP TABLE grupo;
DROP TABLE tema;
DROP TABLE modulo;
DROP TABLE beca;
DROP TABLE aula;
DROP TABLE curso;
DROP TABLE profesor;

CREATE TABLE profesor (
idProf INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombreEmp VARCHAR(45),
telefono VARCHAR(14) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
dni_prof VARCHAR(9) UNIQUE
);

CREATE TABLE curso (
codCurso CHAR(5) NOT NULL PRIMARY KEY,
nomCurso VARCHAR(50) NOT NULL,
nivelEducativo VARCHAR(15) NOT NULL,
CONSTRAINT ckNivel CHECK (nivelEducativo IN('BASICO', 'MEDIO', 'SUPERIOR'))
);

CREATE TABLE aula (
codAula CHAR(10) PRIMARY KEY,
numPlazas INT NOT NULL,
numOrdenadores INT
);

CREATE TABLE beca (
idBeca INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
importe DECIMAL(5,2) NOT NULL,
CONSTRAINT ckImporte CHECK (importe >= 0 AND importe < 1000),
fechaBeca DATE NOT NULL DEFAULT (current_date())
);

CREATE TABLE modulo (
codMod CHAR(5) NOT NULL PRIMARY KEY,
idProf INT NOT NULL,
nomMod VARCHAR(45) NOT NULL,
CONSTRAINT fkModulo FOREIGN KEY (idProf) REFERENCES profesor(idProf) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE tema (
codTema CHAR(5) NOT NULL PRIMARY KEY,
codMod CHAR(5) NOT NULL,
tituloTema VARCHAR(45),
CONSTRAINT fkTema FOREIGN KEY (codMod) REFERENCES modulo(codMod) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE grupo (
codCurso CHAR(5),
letra CHAR(1) NOT NULL,
codAula CHAR(10),
PRIMARY KEY (codCurso, letra),
CONSTRAINT fkGrupo1 FOREIGN KEY (codCurso) REFERENCES curso(codCurso) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fkGrupo2 FOREIGN KEY (codAula) REFERENCES aula(codAula) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE alumno (
codExpediente VARCHAR(10) NOT NULL PRIMARY KEY,
nomAlumno VARCHAR(45),
telAlumno VARCHAR(14),
fechaNacimiento DATE NOT NULL,
codExpedienteDelegado VARCHAR(10),
idBeca INT,
codCurso CHAR(5),
letra CHAR(1),
CONSTRAINT fkAlumno1 FOREIGN KEY (codExpedienteDelegado) REFERENCES alumno(codExpediente) ON UPDATE CASCADE ON DELETE RESTRICT,
CONSTRAINT fkAlumno2 FOREIGN KEY (idBeca) REFERENCES beca(idBeca) ON UPDATE CASCADE ON DELETE RESTRICT,
CONSTRAINT fkAlumno3 FOREIGN KEY (codCurso, letra) REFERENCES grupo(codCurso, letra) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE cursa (
codTema CHAR(5) NOT NULL PRIMARY KEY,
codMod CHAR(5) NOT NULL,
tituloTema CHAR(45),
CONSTRAINT fkCursa FOREIGN KEY (codMod) REFERENCES modulo(codMod) ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE beca ADD COLUMN meses INT;
ALTER TABLE alumno MODIFY COLUMN nomAlumno VARCHAR(50);
ALTER TABLE profesor DROP COLUMN email;
CREATE INDEX idxNivel ON curso(nivelEducativo);
RENAME TABLE tema TO unidad;

DROP USER IF EXISTS 'consulta'@'localhost';
CREATE USER 'consulta'@'localhost' IDENTIFIED BY '12345';
GRANT SELECT ON instituto.* TO 'consulta'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLESPACE tsCatalogo ADD DATAFILE 'tsCatalogo.idb' ENGINE = InnoDB;
ALTER TABLE aula TABLESPACE tsCatalogo;
ALTER TABLE curso TABLESPACE tsCatalogo;